name: MD to PDF

on:
  push:
    paths:
      - 'docs/**/*.md'
      - '.github/workflows/md-to-pdf.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 安裝 Pandoc + XeLaTeX + CJK 字型，支援中文、數學
      - name: Install TeX, Pandoc, Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended \
              texlive-latex-recommended texlive-latex-extra fonts-noto-cjk
          # 可選：安裝思源宋體／黑體名稱（Noto CJK）供中文排版
          fc-list :lang=zh | head || true

      # 轉檔：掃描 docs/*.md → build/pdf/*.pdf
      - name: Convert Markdown to PDF
        run: |
          mkdir -p build/pdf
          for f in docs/*.md; do
            base=$(basename "$f" .md)
            pandoc "$f" \
              --from gfm+yaml_metadata_block \
              --pdf-engine=xelatex \
              -V mainfont="Noto Serif CJK TC" \
              -V monofont="Noto Sans Mono CJK TC" \
              -V geometry:margin=1in \
              -V colorlinks=true \
              --toc \
              -o "build/pdf/${base}.pdf"
          done

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: build/pdf/*.pdf
