name: MD to PDF (md-to-pdf changed-only)

on:
  push:
    branches-ignore:
      - pdf
    paths:
      - '**/*.md'
      - '.github/workflows/md-to-pdf.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Detect changed Markdown files
        id: files
        shell: bash
        run: |
          set -euo pipefail
          BEFORE="${{ github.event.before || '' }}"
          if [ -z "$BEFORE" ]; then BEFORE="$(git rev-parse HEAD~1 || echo '')"; fi
          if [ -n "$BEFORE" ]; then
            CHANGED=$(git diff --name-only "$BEFORE" "$GITHUB_SHA" -- '**/*.md' ':!.github/**' ':!build/**' || true)
          else
            CHANGED=$(git ls-files '**/*.md' ':!.github/**' ':!build/**' || true)
          fi
          echo "changed<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED"

      - name: Skip if no changes
        if: steps.files.outputs.changed == ''
        run: |
          echo "No changed .md files; skipping."
          exit 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install md-to-pdf (and optional mermaid)
        run: |
          npm i -g md-to-pdf @mermaid-js/mermaid-cli

      - name: Build PDFs (changed only)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p build
          while IFS= read -r f; do
            [ -z "$f" ] && continue
            dir="$(dirname "$f")"
            base="$(basename "$f" .md)"
            outdir="build/${dir}"
            mkdir -p "$outdir"
            echo "Converting: $f -> ${outdir}/${base}.pdf"
            # 直接渲染；如需 KaTeX/MathJax，可加 --body-template 引入 CDN
            md-to-pdf "$f" --output "${outdir}/${base}.pdf"
          done <<< "${{ steps.files.outputs.changed }}"

      - name: Publish PDFs to pdf branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          publish_branch: pdf
          force_orphan: true
