name: MD to PDF (to pdf branch)

on:
  push:
    branches-ignore:
      - pdf
    paths:
      - '**/*.md'
      - '.github/workflows/md-to-pdf.yml'
  workflow_dispatch:

# 關鍵：給 GITHUB_TOKEN 寫入 repo 的權限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # 避免覆蓋 peaceiris 使用的 token

      - name: Install TeX, Pandoc, Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended \
              texlive-latex-recommended texlive-latex-extra fonts-noto-cjk

      - name: Build PDFs (mirror folders)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar nullglob
          rm -rf build
          mkdir -p build
          for f in **/*.md; do
            case "$f" in .github/*|build/*) continue ;; esac
            dir="$(dirname "$f")"
            base="$(basename "$f" .md)"
            outdir="build/${dir}"
            mkdir -p "$outdir"
            echo "Converting: $f -> ${outdir}/${base}.pdf"
            pandoc "$f" \
              --from gfm+yaml_metadata_block \
              --pdf-engine=xelatex \
              -V mainfont="Noto Serif CJK TC" \
              -V monofont="Noto Sans Mono CJK TC" \
              -V geometry:margin=1in \
              -V colorlinks=true \
              --toc \
              -o "${outdir}/${base}.pdf"
          done

      - name: Publish PDFs to pdf branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          publish_branch: pdf
          force_orphan: true
